#!/usr/bin/env bash
# scripts/setup-engine.sh — one-shot install of the live axiom-rules-engine engine.
#
# Result:
#   1. Clones TheAxiomFoundation/axiom-rules-engine as a sibling of this repo (if missing).
#   2. Builds the Rust binary in release mode.
#   3. Installs the axiom_rules_engine Python wrapper into compute/.venv.
#   4. Writes compute/.env with AXIOM_RULES_ENGINE_BIN so uvicorn picks up real mode.
#
# Re-running is safe (idempotent on each step).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PARENT_DIR="$(dirname "$REPO_ROOT")"
AXIOM_RULES_DIR="$PARENT_DIR/axiom-rules-engine"
COMPUTE_DIR="$REPO_ROOT/compute"

# Ensure cargo is on PATH even if rustup didn't write to the parent shell.
if ! command -v cargo >/dev/null 2>&1; then
  if [ -x "$HOME/.cargo/bin/cargo" ]; then
    export PATH="$HOME/.cargo/bin:$PATH"
  else
    echo "error: cargo not found. Install Rust via https://rustup.rs first." >&2
    exit 1
  fi
fi

if [ ! -d "$AXIOM_RULES_DIR" ]; then
  echo "→ cloning axiom-rules-engine into $AXIOM_RULES_DIR"
  git clone --depth 1 https://github.com/TheAxiomFoundation/axiom-rules-engine.git "$AXIOM_RULES_DIR"
else
  echo "✓ axiom-rules-engine already cloned at $AXIOM_RULES_DIR"
fi

echo "→ building axiom-rules-engine (release)"
( cd "$AXIOM_RULES_DIR" && cargo build --release )

BIN="$AXIOM_RULES_DIR/target/release/axiom-rules"
if [ ! -x "$BIN" ]; then
  echo "error: build did not produce $BIN" >&2
  exit 1
fi
echo "✓ binary at $BIN"

if [ ! -d "$COMPUTE_DIR/.venv" ]; then
  echo "→ creating compute venv"
  ( cd "$COMPUTE_DIR" && uv venv && uv pip install -e . )
fi

echo "→ installing axiom_rules_engine python wrapper into compute/.venv"
( cd "$COMPUTE_DIR" && uv pip install -e "$AXIOM_RULES_DIR/python" )

ENV_FILE="$COMPUTE_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/setup-engine.sh. Edit if your paths differ.
AXIOM_RULES_ENGINE_BIN=$BIN
AXIOM_RULESPEC_ROOT=$PARENT_DIR
AXIOM_RULESPEC_REPO_ROOTS=$PARENT_DIR
RENDERER_URL=http://127.0.0.1:5174
EOF
echo "✓ wrote $ENV_FILE"

# Federal rule packs imported by most state policies.
for repo in rulespec-us rulespec-us-co; do
  if [ ! -d "$PARENT_DIR/$repo" ]; then
    echo "→ cloning $repo (needed for cross-jurisdiction imports)"
    git clone --depth 1 "https://github.com/TheAxiomFoundation/$repo.git" "$PARENT_DIR/$repo"
  else
    echo "✓ $repo already cloned"
  fi
done

cat <<'EOF'

  Engine ready.

  Restart compute:
    cd compute && uv run uvicorn main:app --port 8787 --reload

  Verify with:
    curl -s http://127.0.0.1:8787/healthz | python3 -m json.tool

  Expect "mode": "real". Demo-mode pill in the UI will disappear.
EOF
